// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3k7ehAk64_W0CQkGCF2oxKI_yMtNpOBc',
    appId: '1:908080166424:web:da45d8e5d4f38c8d09356d',
    messagingSenderId: '908080166424',
    projectId: 'oblako-12c79',
    authDomain: 'oblako-12c79.firebaseapp.com',
    storageBucket: 'oblako-12c79.firebasestorage.app',
    measurementId: 'G-J2EKJTL747',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzuekcKdYZmq6pPajYuPgQkkhc2Ta0v8c',
    appId: '1:908080166424:android:a91d08f1b84f8e5e09356d',
    messagingSenderId: '908080166424',
    projectId: 'oblako-12c79',
    storageBucket: 'oblako-12c79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFk62rYE1j99M3hBKjYuBAIUsR85b1DcM',
    appId: '1:908080166424:ios:4dc8e3bb434f7dc609356d',
    messagingSenderId: '908080166424',
    projectId: 'oblako-12c79',
    storageBucket: 'oblako-12c79.firebasestorage.app',
    iosBundleId: 'com.devclub.culinarium',
  );
}
